version: "3.8"
services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$BD_PASSWORD
      - MYSQL_DATABASE=$BD_NOMBRE
    ports:
      - "3307:3306"
  app:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "3001:3001"
